export type ResearchToolCategoryId =
  | 'market-intel'
  | 'onchain-intel'
  | 'fundraising-unlocks'
  | 'airdrop-research';

export interface ResearchToolCategory {
  id: ResearchToolCategoryId;
  label: string;
  kicker: string;
  description: string;
  accent: string;
}

export interface ResearchToolEntry {
  id: string;
  name: string;
  description: string;
  url: string;
  logo: string;
  accent: string;
  categoryId: ResearchToolCategoryId;
  availability: 'Free' | 'Free / Freemium';
  bestFor: string;
  tags: string[];
  featured?: boolean;
}

export const researchToolCategories: ResearchToolCategory[] = [
  {
    id: 'market-intel',
    label: 'Market Intel',
    kicker: 'Pricing, sector map, and protocol snapshots',
    description: 'Tool inti untuk baca market, kapitalisasi, fundamentals, dan overview sektor.',
    accent: '#b8c1ec',
  },
  {
    id: 'onchain-intel',
    label: 'Onchain Intel',
    kicker: 'Wallets, flows, dashboards, and usage heat',
    description: 'Cocok untuk cek wallet, usage, volume, TVL, dan perilaku user onchain.',
    accent: '#b8c1ec',
  },
  {
    id: 'fundraising-unlocks',
    label: 'Fundraising & Unlocks',
    kicker: 'VC data, token schedules, and project pipelines',
    description: 'Untuk riset funding, investor map, unlock calendar, dan listing project baru.',
    accent: '#eebbc3',
  },
  {
    id: 'airdrop-research',
    label: 'Airdrop Research',
    kicker: 'Hunters workflow, watchlists, and farming references',
    description: 'Deck untuk cari peluang, tracking eligibility, dan riset farming flow.',
    accent: '#eebbc3',
  },
];

export const researchToolsDirectory: ResearchToolEntry[] = [
  {
    id: 'coingecko',
    name: 'CoinGecko',
    description: 'Harga, market cap, kategori token, dan narasi market secara luas.',
    url: 'https://www.coingecko.com/',
    logo: '/logos/coingecko.png',
    accent: '#b8c1ec',
    categoryId: 'market-intel',
    availability: 'Free',
    bestFor: 'Sector scan dan market pulse cepat',
    tags: ['Prices', 'Categories', 'Market Cap'],
    featured: true,
  },
  {
    id: 'coinmarketcap',
    name: 'CoinMarketCap',
    description: 'Data ranking token, exchange, narratives, dan mover market harian.',
    url: 'https://coinmarketcap.com/',
    logo: '/logos/cmc.png',
    accent: '#b8c1ec',
    categoryId: 'market-intel',
    availability: 'Free',
    bestFor: 'Ranking dan heatmap market',
    tags: ['Rankings', 'Narratives', 'Exchanges'],
  },
  {
    id: 'tokenterminal',
    name: 'Token Terminal',
    description: 'Fundamental protocol, revenue, fees, valuation, dan comparable metrics.',
    url: 'https://tokenterminal.com/',
    logo: '/logos/tokenterminal.png',
    accent: '#b8c1ec',
    categoryId: 'market-intel',
    availability: 'Free / Freemium',
    bestFor: 'Valuation dan protocol earnings',
    tags: ['Revenue', 'Fees', 'Valuation'],
    featured: true,
  },
  {
    id: 'messari',
    name: 'Messari',
    description: 'Research primer, market intelligence, governance, dan protocol thesis.',
    url: 'https://messari.io/',
    logo: '/logos/messari.png',
    accent: '#b8c1ec',
    categoryId: 'market-intel',
    availability: 'Free / Freemium',
    bestFor: 'Deep research dan token thesis',
    tags: ['Research', 'Governance', 'Reports'],
  },
  {
    id: 'coincodex',
    name: 'CoinCodex',
    description: 'Harga, sentimen, dan watchlist sederhana untuk tracking coin rotation.',
    url: 'https://coincodex.com/',
    logo: '/logos/coincodex.png',
    accent: '#eebbc3',
    categoryId: 'market-intel',
    availability: 'Free',
    bestFor: 'Fast watchlist dan alerts',
    tags: ['Prices', 'Watchlist', 'Sentiment'],
  },
  {
    id: 'cryptocompare',
    name: 'CryptoCompare',
    description: 'Reference market data, index, dan pembanding aset lintas exchange.',
    url: 'https://www.cryptocompare.com/',
    logo: '/logos/cryptocompare.png',
    accent: '#b8c1ec',
    categoryId: 'market-intel',
    availability: 'Free',
    bestFor: 'Cross-market reference',
    tags: ['Data', 'Indexes', 'Compare'],
  },
  {
    id: 'defillama',
    name: 'DefiLlama',
    description: 'TVL, fees, bridged volume, stablecoins, unlocks, dan airdrop monitor.',
    url: 'https://defillama.com/',
    logo: '/logos/defillama.png',
    accent: '#b8c1ec',
    categoryId: 'onchain-intel',
    availability: 'Free',
    bestFor: 'Protocol health dan ecosystem scan',
    tags: ['TVL', 'Fees', 'Yields'],
    featured: true,
  },
  {
    id: 'dune',
    name: 'Dune',
    description: 'Dashboard SQL buat baca transaksi, user growth, token flow, dan behavior.',
    url: 'https://dune.com/',
    logo: '/logos/dune.png',
    accent: '#d4d8f0',
    categoryId: 'onchain-intel',
    availability: 'Free / Freemium',
    bestFor: 'Custom dashboard dan wallet tracking',
    tags: ['Dashboards', 'Queries', 'Wallets'],
    featured: true,
  },
  {
    id: 'artemis',
    name: 'Artemis',
    description: 'Network metrics, stablecoin flow, active addresses, dan developer trends.',
    url: 'https://www.artemisanalytics.com/',
    logo: '/logos/artemis.png',
    accent: '#b8c1ec',
    categoryId: 'onchain-intel',
    availability: 'Free / Freemium',
    bestFor: 'Chain comparison dan stablecoin flow',
    tags: ['Chains', 'Stablecoins', 'Usage'],
  },
  {
    id: 'dexscreener',
    name: 'DEX Screener',
    description: 'Monitor pair baru, volume, liquidity, dan rotasi token secara real-time.',
    url: 'https://dexscreener.com/',
    logo: '/logos/dex.png',
    accent: '#b8c1ec',
    categoryId: 'onchain-intel',
    availability: 'Free',
    bestFor: 'Launch radar dan pair discovery',
    tags: ['Pairs', 'Volume', 'Launches'],
  },
  {
    id: 'debank',
    name: 'DeBank',
    description: 'Portfolio tracker publik, smart money watchlist, dan identity layer wallet.',
    url: 'https://debank.com/',
    logo: '/logos/debank.png',
    accent: '#eebbc3',
    categoryId: 'onchain-intel',
    availability: 'Free',
    bestFor: 'Wallet scan dan smart money check',
    tags: ['Portfolio', 'Wallets', 'Identity'],
  },
  {
    id: 'arkham',
    name: 'Arkham',
    description: 'Entity tracking, wallet clusters, alerts, dan deanonymized onchain intel.',
    url: 'https://www.arkhamintelligence.com/',
    logo: '/logos/arkham.png',
    accent: '#b8c1ec',
    categoryId: 'onchain-intel',
    availability: 'Free',
    bestFor: 'Entity mapping dan whale tracking',
    tags: ['Wallet Labels', 'Alerts', 'Entities'],
  },
  {
    id: 'github',
    name: 'GitHub Trending',
    description: 'Track repo, commit velocity, dan builder signals sebelum project meledak.',
    url: 'https://github.com/trending',
    logo: '/logos/github.png',
    accent: '#fffffe',
    categoryId: 'onchain-intel',
    availability: 'Free',
    bestFor: 'Builder activity dan repo health',
    tags: ['Repos', 'Commits', 'Builders'],
  },
  {
    id: 'cryptorank',
    name: 'CryptoRank',
    description: 'Fundraising, token sale, unlocks, vesting, dan calendar listing project.',
    url: 'https://cryptorank.io/',
    logo: '/logos/crypto rank.png',
    accent: '#b8c1ec',
    categoryId: 'fundraising-unlocks',
    availability: 'Free / Freemium',
    bestFor: 'Vesting dan fundraiser map',
    tags: ['Unlocks', 'Fundraising', 'Calendar'],
    featured: true,
  },
  {
    id: 'rootdata',
    name: 'RootData',
    description: 'Project directory, investor graph, fundraising rounds, dan event calendar.',
    url: 'https://www.rootdata.com/',
    logo: '/logos/rootdata.png',
    accent: '#b8c1ec',
    categoryId: 'fundraising-unlocks',
    availability: 'Free',
    bestFor: 'Investor relations dan project discovery',
    tags: ['Projects', 'Investors', 'Calendar'],
  },
  {
    id: 'tokenomist',
    name: 'Token Unlocks',
    description: 'Jadwal vesting, token release, supply pressure, dan upcoming unlock events.',
    url: 'https://token.unlocks.app/',
    logo: '/logos/tokenomist.png',
    accent: '#eebbc3',
    categoryId: 'fundraising-unlocks',
    availability: 'Free',
    bestFor: 'Unlock calendar dan supply pressure',
    tags: ['Unlocks', 'Vesting', 'Supply'],
  },
  {
    id: 'airdrops-io',
    name: 'Airdrops.io',
    description: 'Listing airdrop aktif, step-by-step farming, dan watchlist opportunity.',
    url: 'https://airdrops.io/',
    logo: '/logos/airdrops.png',
    accent: '#232946',
    categoryId: 'airdrop-research',
    availability: 'Free',
    bestFor: 'Opportunity watchlist',
    tags: ['Listings', 'Guides', 'Farming'],
  },
  {
    id: 'bankless',
    name: 'Bankless',
    description: 'Guides eligibility, thematic research, dan update peluang airdrop besar.',
    url: 'https://www.bankless.com/',
    logo: '/logos/bank.png',
    accent: '#eebbc3',
    categoryId: 'airdrop-research',
    availability: 'Free / Freemium',
    bestFor: 'Narrative guide dan eligibility content',
    tags: ['Guides', 'Eligibility', 'Themes'],
  },
  {
    id: 'dropsearn',
    name: 'Dropsearn',
    description: 'Tracker farming route, potential reward, dan dashboard progress hunter.',
    url: 'https://dropsearn.com/',
    logo: '/logos/dropsearn.png',
    accent: '#b8c1ec',
    categoryId: 'airdrop-research',
    availability: 'Free',
    bestFor: 'Farming route dan tracker',
    tags: ['Tracker', 'Routes', 'Rewards'],
  },
  {
    id: 'airdropalert',
    name: 'Airdrop Alert',
    description: 'Notifikasi peluang baru, campaigns, dan resource airdrop pemula sampai lanjut.',
    url: 'https://airdropalert.com/',
    logo: '/logos/airdropalert.png',
    accent: '#b8c1ec',
    categoryId: 'airdrop-research',
    availability: 'Free',
    bestFor: 'Opportunity feed cepat',
    tags: ['Alerts', 'Campaigns', 'Feed'],
  },
  {
    id: 'airdropsmob',
    name: 'AirdropsMob',
    description: 'Kalender peluang, bounty, dan update farming yang lebih ringan dan cepat.',
    url: 'https://airdropsmob.com/',
    logo: '/logos/airdropsmob.png',
    accent: '#eebbc3',
    categoryId: 'airdrop-research',
    availability: 'Free',
    bestFor: 'Calendar dan quick checks',
    tags: ['Calendar', 'Bounties', 'News'],
  },
  {
    id: 'freeairdrop',
    name: 'FreeAirdrop',
    description: 'List bounty dan airdrop gratis untuk tambahan sumber cross-check.',
    url: 'https://freeairdrop.io/',
    logo: '/logos/freeairdrop.png',
    accent: '#eebbc3',
    categoryId: 'airdrop-research',
    availability: 'Free',
    bestFor: 'Extra source buat cross-check',
    tags: ['Bounties', 'Listings', 'Cross-check'],
  },
];
